apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: student0
  annotations:
    kubernetes.io/ingress.class: "tectonic"
spec:
  rules:
    - host: hello-world.workshop04.sm.se.k8s.work
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-world
              servicePort: 80
