apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: studentX
  annotations:
    kubernetes.io/ingress.class: "tectonic"
spec:
  rules:
    - host: hello-world.workshop05.se.aws.event-cloud.net
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-world
              servicePort: 80
