apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.36.112
    path: "/nfs/data"
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
