kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aws-ebs-sc-pvc-x
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-ebs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
